import os
import sys
import yaml
from pathlib import Path

SEED_TEMPLATE = """# LMF Instance — Seed Profile (generated by init wizard)
# Replace remaining ((placeholders)) before deploying.

operator:
  name: "((OPERATOR_NAME))"
  email: "((OPERATOR_EMAIL))"
  phone: "((OPERATOR_PHONE))"

vault:
  root: "((VAULT_ROOT))"
  state_path: "((STATE_PATH))"

ntfy:
  url: "((NTFY_URL))"
  topic: "((NTFY_TOPIC))"

panels:
  - panel.marlin
  - panel.ai-chat
  - panel.ttf
  - panel.ink-blotter
  - panel.terminal
  - panel.vault
  - panel.projects
  - panel.quickhacks
  - panel.scribner

skills:
  - skill.marlin-capture
  - skill.marlin-enrich
  - skill.marlin-open
  - skill.marlin-close
  - skill.ttf-push
  - skill.marlin-learn
  - skill.project-reload
  - skill.scribe-digest

endpoints:
  marlin: "((HOST_MARLIN))"
  ai_chat: "((HOST_AI_CHAT))"
  ttf: "((HOST_TTF))"
  ink_blotter: "((HOST_INK))"
  terminal: "((HOST_TERMINAL))"
  vault: "((HOST_VAULT))"
  projects: "((HOST_PROJECTS))"
  quickhacks: "((HOST_QUICKHACKS))"
  scribner: "((HOST_SCRIBNER))"
"""


def detect_os():
    if sys.platform == "win32":
        return "windows"
    if sys.platform == "darwin":
        return "macos"
    return "linux"


def detect_wsl():
    if sys.platform != "linux":
        return False
    try:
        with open("/proc/version") as f:
            return "microsoft" in f.read().lower() or "wsl" in f.read().lower()
    except FileNotFoundError:
        return False


def suggest_vault_root():
    plat = detect_os()
    is_wsl = detect_wsl()

    if is_wsl:
        return "/mnt/c/Users/<username>/Documents/Scribner"
    if plat == "windows":
        return "C:\\Users\\<username>\\Documents\\Scribner"
    if plat == "macos":
        return "/Users/<username>/Documents/Scribner"
    return "/home/<username>/Documents/Scribner"


def prompt(prompt_text, default=None, validator=None):
    if default:
        full = f"{prompt_text} [{default}]: "
    else:
        full = f"{prompt_text}: "
    try:
        value = input(full).strip()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(1)
    if not value and default:
        return default
    if not value:
        return ""
    if validator and not validator(value):
        print(f"  Invalid input. {validator.__doc__}")
        return prompt(prompt_text, default, validator)
    return value


def path_exists_validator(path):
    """Path must exist and be a directory."""
    expanded = os.path.expanduser(path)
    return os.path.isdir(expanded)


def yes_no(prompt_text, default=True):
    hint = "Y/n" if default else "y/N"
    value = input(f"{prompt_text} [{hint}]: ").strip().lower()
    if not value:
        return default
    return value in ("y", "yes")


def run_wizard(output_path=None):
    print()
    print("╔══════════════════════════════════════════════════╗")
    print("║     LMF Init Wizard — Create a Seed Profile     ║")
    print("╚══════════════════════════════════════════════════╝")
    print()

    plat = detect_os()
    is_wsl = detect_wsl()
    print(f"Detected platform: {plat}" + (" (WSL)" if is_wsl else ""))
    print()

    # Phase 1: Operator identity
    print("--- Operator Identity ---")
    name = prompt("Operator name")
    email = prompt("Operator email")
    phone = prompt("Operator phone")
    git_org = prompt("Git organization (for clone URLs)", default="{{GIT_ORG}}")
    print()

    # Phase 2: Vault config
    print("--- Vault Configuration ---")
    suggested = suggest_vault_root()
    vault_root = prompt(
        "Vault root path",
        default=suggested,
        validator=path_exists_validator
    )
    state_path = prompt("State file path", default=f"{vault_root}/../state.json")

    print()
    print("--- Ntfy Notifications (optional) ---")
    use_ntfy = yes_no("Configure Ntfy push notifications?", default=False)
    ntfy_url = ""
    ntfy_topic = ""
    if use_ntfy:
        ntfy_url = prompt("Ntfy server URL", default="http://localhost:8086")
        ntfy_topic = prompt("Ntfy topic")
    print()

    print("--- Service Endpoints ---")
    print("(Press Enter to accept default)")
    hosts = {}
    for service in [
        ("marlin", "8000"),
        ("ai_chat", "8010"),
        ("ttf", "8020"),
        ("ink_blotter", "8030"),
        ("terminal", "8040"),
        ("vault", "8050"),
        ("projects", "8060"),
        ("quickhacks", "8070"),
        ("scribner", "8080"),
    ]:
        srv, port = service
        default = f"http://localhost:{port}"
        hosts[srv] = prompt(f"{srv} URL", default=default)

    print()
    print("--- Summary ---")
    summary = f"""  Operator: {name or '((OPERATOR_NAME))'}
  Email:    {email or '((OPERATOR_EMAIL))'}
  Phone:    {phone or '((OPERATOR_PHONE))'}
  Vault:    {vault_root or '((VAULT_ROOT))'}
  State:    {state_path or vault_root + '/../state.json'}
  Ntfy:     {'yes — ' + ntfy_url + '/' + ntfy_topic if use_ntfy else 'no'}
  Panels:   9 (default set)
  Skills:   10 (default set)"""
    print(summary)
    print()

    if not yes_no("Write this profile?", default=True):
        print("Cancelled.")
        sys.exit(0)

    # Build the profile YAML
    profile = {
        "operator": {
            "name": name or "((OPERATOR_NAME))",
            "email": email or "((OPERATOR_EMAIL))",
            "phone": phone or "((OPERATOR_PHONE))",
        },
        "vault": {
            "root": vault_root or "((VAULT_ROOT))",
            "state_path": state_path or f"{vault_root}/../state.json",
        },
        "panels": [
            "panel.marlin", "panel.ai-chat", "panel.ttf",
            "panel.ink-blotter", "panel.terminal", "panel.vault",
            "panel.projects", "panel.quickhacks", "panel.scribner",
        ],
        "skills": [
            "skill.marlin-capture", "skill.marlin-enrich",
            "skill.marlin-open", "skill.marlin-close",
            "skill.ttf-push", "skill.marlin-learn",
            "skill.project-reload", "skill.scribe-digest",
        ],
        "endpoints": hosts,
    }

    # Determine output path
    if not output_path:
        output_path = input(f"Output path [scribner/seed_profile.local.yaml]: ").strip()
        if not output_path:
            output_path = "scribner/seed_profile.local.yaml"

    output_path = os.path.expanduser(output_path)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    with open(output_path, "w") as f:
        yaml.dump(profile, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
        # Append a comments block
        f.write("\n# Generated by LMF Init Wizard\n")

    print(f"\n✓ Profile written to {output_path}")

    if yes_no("Validate this profile against the registry?", default=True):
        from .manager import cmd_validate
        print()
        cmd_validate({})

    print()
    print("Next: set environment variables and run:")
    print(f"  python3 -m features.feature_manager.manager install --profile {output_path}")
    print()


if __name__ == "__main__":
    run_wizard()
